config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  resources :products
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end

  get 'profile' => 'users#show'

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, :category, presence: true
	validates :price_in_cents, numericality: {only_integer: true}

	has_many :reviews
	has_many :users, through: :reviews

	scope :newest_first, -> {order("created_at DESC")}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f", price_in_dollars)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name, presence: true
	

	has_many :reviews
	has_many :products, through: :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id] # if there is a coockie set up for this do that otherwise log in
  end #if no one is logged in return nil

  helper_method :current_user #tells rails to also use this as a helper method to be available in views

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @most_recent_product_order = Product.newest_first
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)

  	if @product.save
  		redirect_to products_url
  	else
  		render :new
  	end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
	end

	private
	def product_params
		params.require(:product).permit(:name, :description, :price_by_cents, :category)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :ensure_logged_in, only: [:create, :destroy]
  before_filter :load_product


  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user = current_user
  	if @review.save
  		redirect_to products_path, notice: "Review created successfully"
  	else
  		render "products/show"
  	end
  end

  def destroy
  	@review = Review.find (params[:id])
  	@review.destroy
  end

  private
  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create #capturing the password and matching it to the user.
  	user = User.find_by(email: params[:email]) #.find only looks up id's so you need find by email to find by a string
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id #this logs us in
      redirect_to products_url, notice: "Logged in!"
    else
    	flash.now[:alert] = "invalid email or password"
      render "new"
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Signed up" # sinonymous to :notice = "Signed up"
      session[:user_id] = @user.id #to also log in after we have signed up
      redirect_to products_url
    else
      flash.now[:alert] = "oh, something bad happened."
      render "new"
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img src="https://cdn0.iconfinder.com/data/icons/shopping-set-4/512/10-512.png" height="40px" width="40px">
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Log out", session_path("current"), :method => :delete %><li>
          <li><%= link_to "My Profile", profile_path %></li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %></li>
          <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Rainforest</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body class="<%= controller_name %> <%= action_name %>">

		<%= render 'layouts/header' %>

		<% if flash[:notice] %>
			<p id="notice"><%= flash[:notice] %></p>
		<% end %>
		<% if flash[:alert] %>
			<p id="alert"><%= flash[:alert] %></p>
		<% end %>

		<%= yield %>

		<p class="userinfo">
			<% if current_user %>
				Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %> | 
				<%= link_to "Profile", profile_path %>
			<% else %>
				<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
			<% end %>		
		</p>

	</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

	<% if @product.errors.any? %>
		<div id="error_explenation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved: </h2>
			<ul>
				<% @product.errors.full_message.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %><br/>
		<%= f.text_field :description %>
	</div>
	<div class="field">
		<%= f.label :category %><br/>
		<%= f.text_field :category %>
	</div>
	<div class="field">
		<%= f.label :price_by_cents %><br/>
		<%= f.number_field :price_in_cents %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/products/_review_display.html.erb
<p>Reviews for <%= @product.name %></p>

<% @product.reviews.each do |review| %>
	<p>
		<%= review.comment %>
		<br>
		<% if review.user != nil %>
			<em> by <%= review.user.name %></em>
			Added on: <%= review.created_at %>
		<% end %>
	</p>
<% end %>

app/views/products/_review_form.html.erb
<%= form_for([@product, @review]) do |f| %>

	<% if @review.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

			<ul>
				<% @review.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :comment %><br/>
		<%= f.text_area :comment %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
	
<% end %>	

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>ALL Products</h1>

<% @products.each do |product| %>

	<div class="media">
	  <a class="media-left media-middle" href="#">
	    <img src="http://www.apetogentleman.com/wp-content/uploads/2010/08/neals-yard-remedies-soothing-starflower.jpg" width="64px" height="64px">
	  </a>
	  <div class="media-body">
	    <h4 class="media-heading"><%= product.name %></h4>
	    <p><%= product.description %></p>
	    <p><%= product.formatted_price %></p>
	  </div>
	</div>

<%end%>

app/views/products/new.html.erb
<h1>Create New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product Information</h1>


<p><%= @product.name %> <%= @product.description %> <%= @product.formatted_price %></p>

<% if @current_user %>

	<h3>Reviews</h3>

	<%= render 'review_display' %>

	<h4>New Review</h4>

	<%= render 'review_form' %>	

<% else %>
	<p>Please <%= link_to "Log in", new_session_path %> to add a review.</p>
<% end %>

<%= link_to 'Back', products_path %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<ul class="list-group">
	<li class="list-group-item" id="a">Your Details</li>
  <li class="list-group-item"><%= @user.name %></li>
  <li class="list-group-item"><%= @user.email %></li>
  <li class="list-group-item">Signed up on <%= @user.created_at %></li>
  
</ul>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Your Product Reviews</h3>
  </div>
  <div class="panel-body">
	  reviews

	</div>
</div>